// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjAbYWgJiIOW8rhsZCr8XkaTw9awKFr0',
    appId: '1:178894714744:android:1515f65d71b41559c1fa8d',
    messagingSenderId: '178894714744',
    projectId: 'fir-demo-authentication',
    storageBucket: 'fir-demo-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7WAtQTZblwgTvliEYv_cZZ9dkptQuBk4',
    appId: '1:178894714744:ios:f1cbd80dc81f9cd9c1fa8d',
    messagingSenderId: '178894714744',
    projectId: 'fir-demo-authentication',
    storageBucket: 'fir-demo-authentication.appspot.com',
    iosClientId: '178894714744-7qm7fqi8uhh3tdgsih2arfl35qav75cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7WAtQTZblwgTvliEYv_cZZ9dkptQuBk4',
    appId: '1:178894714744:ios:f1cbd80dc81f9cd9c1fa8d',
    messagingSenderId: '178894714744',
    projectId: 'fir-demo-authentication',
    storageBucket: 'fir-demo-authentication.appspot.com',
    iosClientId: '178894714744-7qm7fqi8uhh3tdgsih2arfl35qav75cc.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoAuthentication',
  );
}
